name: Publish NPM Package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Node.js Version
        uses: actions/setup-node@v2
        with:
          node-version: 18
          
      - name: Install Dependencies
        run: npm install
        
      - name: Unit Tests
        run: npm run test

      - name: Publish To NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
          npm publish --access public

    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      